# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lawrence Andrews' Blog
email: lawrence@lawrenceandrews.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Problems encountered in the daily life of a Software Engineer (Mostly Java, Raspberry pi
  and unix/server related)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lenny151.github.io" # the base hostname & protocol for your site
github_username:  lenny151

# Build settings
markdown: kramdown
